const funFacts = [
  // Technology & Computing (1-20)
  "Did you know that the first computer virus was created in 1983?",
  "Did you know that the first car was invented in 1885?",
  "The first webcam was created to monitor a coffee pot at Cambridge University.",
  "Email existed before the World Wide Web.",
  "The first computer bug was an actual bug - a moth trapped in a Harvard Mark II computer in 1947.",
  "The QWERTY keyboard was designed to slow down typing to prevent typewriter jams.",
  "The first computer mouse was made of wood.",
  "The @ symbol was chosen for email addresses because it was rarely used in names.",
  "The first domain name ever registered was symbolics.com in 1985.",
  "There are more possible iterations of a game of chess than there are atoms in the observable universe.",
  "The first 1GB hard drive, announced in 1980, weighed about 550 pounds and cost $40,000.",
  "The first computer programmer was Ada Lovelace, a woman who lived in the 1800s.",
  "The Firefox logo isn't actually a fox - it's a red panda.",
  "The word 'robot' comes from the Czech word 'robota' which means forced labor.",
  "The first known computer algorithm was written by Ada Lovelace in 1843.",
  "Google's original name was Backrub.",
  "The first website is still online at http://info.cern.ch/hypertext/WWW/TheProject.html",
  "Amazon was originally called Cadabra.",
  "The first YouTube video was uploaded on April 23, 2005, and is titled 'Me at the zoo'.",
  "The most expensive domain name ever sold was Cars.com for $872 million.",

  // Science & Nature (21-40)
  "A day on Venus is longer than its year.",
  "Honey never spoils - archaeologists have found 3000-year-old honey that's still edible.",
  "Octopuses have three hearts and blue blood.",
  "Bananas are berries, but strawberries aren't.",
  "The human brain uses about 20% of the body's total energy.",
  "Lightning strikes the Earth about 100 times per second.",
  "A single bolt of lightning contains enough energy to toast 100,000 slices of bread.",
  "The Amazon rainforest produces 20% of the world's oxygen.",
  "Sound travels 4 times faster in water than in air.",
  "The Great Wall of China isn't visible from space without aid.",
  "Antarctica is the world's largest desert.",
  "The human eye can distinguish about 10 million different colors.",
  "Your body contains about 37.2 trillion cells.",
  "Glass is neither a solid nor a liquid - it's an amorphous solid.",
  "Water can boil and freeze at the same time in a process called the triple point.",
  "The sun loses about 4 million tons of mass every second.",
  "There are more trees on Earth than stars in the Milky Way galaxy.",
  "A teaspoon of neutron star material would weigh about 6 billion tons.",
  "Sharks have been around longer than trees.",
  "The human stomach produces a new lining every 3-4 days.",

  // History & Culture (41-60)
  "The shortest war in history lasted only 38-45 minutes.",
  "Oxford University is older than the Aztec Empire.",
  "Cleopatra lived closer in time to the Moon landing than to the construction of the pyramids.",
  "The ancient Romans used urine as mouthwash.",
  "Vikings didn't wear horned helmets.",
  "The Great Fire of London in 1666 destroyed 13,200 houses but only killed 6 people.",
  "Bubble wrap was originally invented as wallpaper.",
  "Ketchup was once sold as medicine.",
  "The Eiffel Tower can grow up to 6 inches taller in summer due to thermal expansion.",
  "Nintendo was founded in 1889 as a playing card company.",
  "Harvard University was founded before calculus was invented.",
  "The oldest known customer complaint is on a clay tablet from ancient Babylon.",
  "Ancient Egyptians used dead mice to treat toothaches.",
  "The world's oldest known joke is a Sumerian fart joke from 1900 BC.",
  "Beethoven continued composing music even after he went deaf.",
  "The shortest commercial flight in the world lasts just 57 seconds.",
  "More people have mobile phones than toilets globally.",
  "The word 'sandwich' comes from the Earl of Sandwich who invented it so he could eat while gambling.",
  "Ancient Greek athletes competed naked in the Olympics.",
  "The Great Pyramid was the tallest building in the world for over 3,800 years.",

  // Animals & Wildlife (61-80)
  "Cows have best friends and get stressed when separated from them.",
  "A group of flamingos is called a 'flamboyance'.",
  "Dolphins have names for each other.",
  "Penguins propose to their mates with pebbles.",
  "Sea otters hold hands while sleeping to keep from drifting apart.",
  "Wombat poop is cube-shaped.",
  "Butterflies taste with their feet.",
  "A shrimp's heart is in its head.",
  "Elephants are the only animals that can't jump.",
  "A blue whale's heart is so large a human could crawl through its arteries.",
  "Polar bears have black skin under their white fur.",
  "Owls don't have eyeballs - they have eye tubes.",
  "A group of crows is called a 'murder'.",
  "Horses can't vomit.",
  "Koala fingerprints are so similar to human fingerprints they could confuse crime scene investigators.",
  "A snail can sleep for three years.",
  "All polar bears are left-handed.",
  "A cat has 32 muscles in each ear.",
  "Giraffes have the same number of neck vertebrae as humans.",
  "Male seahorses give birth to their young.",

  // Random & Quirky Facts (81-100)
  "There's a basketball court on the top floor of the U.S. Supreme Court building.",
  "The dot over the letter 'i' is called a tittle.",
  "You can't hum while holding your nose.",
  "The fear of long words is called Hippopotomonstrosesquippedaliophobia.",
  "Maine is the closest U.S. state to Africa.",
  "A 'jiffy' is an actual unit of time - 1/100th of a second.",
  "The plastic tips on shoelaces are called aglets.",
  "There are more fake flamingos than real flamingos in the world.",
  "The King of Hearts is the only king in a deck of cards without a mustache.",
  "A group of pandas is called an 'embarrassment'.",
  "The shortest complete sentence in English is 'Go.'",
  "The word 'set' has the most definitions in the English language.",
  "Bubble gum is pink because that was the only dye available when it was invented.",
  "The moon is moving away from Earth at about 1.5 inches per year.",
  "There's a town in Norway called Hell, and it freezes over every winter.",
  "The hashtag symbol is technically called an octothorpe.",
  "You're always looking at your nose - your brain just ignores it.",
  "The average person walks the equivalent of three times around the world in their lifetime.",
  "A single strand of spaghetti is called a spaghetto.",
  "The longest word you can type using only your left hand is 'stewardesses'."
];

module.exports = funFacts;